name: Build pipeline for CFS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: build
        run: go build -v ./...
